In [1]:
# Titanic Aprendizado de maquina sobre o desatre:
# Objetivos: fazer uma previsao de sobreviventes atraves dos dados atraves da Acuracia(A porcentagem de passageiros que se preve corretamente)


# Comecando a entender a base de dados

# importando a base de dados
import pandas as pd
import numpy as np


treino = pd.read_csv("train.csv") # importando a base de dados de treino 
treino.head(3)                    # visualizando a base de treino

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [2]:
# importando o ReportProfiling do ydata-profiling
from ydata_profiling import ProfileReport

c:\Users\cleber\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# gerando o relatorio do profile
profile = ProfileReport(treino, title="Relatorio Treino")

In [4]:
# criando o relatorio
profile.to_file("Relatorio Treino.html")

Summarize dataset:   0%|          | 0/17 [00:00<?, ?it/s, Describe variable: PassengerId]

Export report to file: 100%|██████████| 1/1 [00:00<00:00, 28.51it/s]


In [5]:
# verificando as informacoes da base 
treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
# verificando os tipos de dados
treino.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [7]:
# verificando valores nulos
treino.isnull().sum().sort_values(ascending=False).head(5)
# isnull() retorna True/False para cada célula: / True → o valor é nulo (NaN) / False → o valor não é nulo
# sum() ele retorna a soma dos valores nulos existentes em cada coluna
# sort_values(acending) ele retorna em ordem crescente, as colunas com mais valores nulos aparecem primeiro
# head(5) ira retornar as 5 colunas com mais valores nulos


Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

** agora vamos visualizar a base de teste ** 
A base de teste é a base aonde iremos fazer a previsao

In [8]:
# importando a base de teste
teste = pd.read_csv("test.csv")
teste.head(3)

PassengerId  Pclass                              Name     Sex   Age  SibSp  \
0          892       3                  Kelly, Mr. James    male  34.5      0   
1          893       3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   
2          894       2         Myles, Mr. Thomas Francis    male  62.0      0   

   Parch  Ticket    Fare Cabin Embarked  
0      0  330911  7.8292   NaN        Q  
1      0  363272  7.0000   NaN        S  
2      0  240276  9.6875   NaN        Q

In [9]:
# verificando as informacoes da base de teste
teste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB


In [10]:
# verificando os valores nulos da base ( Apesar de os dados serem os mesmos da base de treino nao necessariamente os valores vazios irao ser iguais entao precisaremos fazer o tratamento de dados dessas 2 bases)
teste.isnull().sum().sort_values(ascending=False).head(5)


Cabin     327
Age        86
Fare        1
Name        0
Pclass      0
dtype: int64

In [11]:
# temos colunas vazias na base de teste que nao estao vazias na base de treino nesse caso entao precisamos tratar somente as colunas da base de teste)
# Realizando o tratamento iniciais dos dados na base de teste

In [12]:
# verificando novamente os valores vazios para a base de treino
treino.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

In [13]:
# retornando o shape da base (quantas linhas,colunas que eu tenho?)
treino.shape

(891, 12)

In [14]:
# entao vemos que de 891 linhas na base temos 687 linhas vazias

# olhando novamente a base 
treino.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [15]:
# vemos que as colunas cabin, ticket as informacoes estao sem padrao ( pode verificar o Relatorio treino.html para visualizar melhor)

In [16]:
# verificando a cardinalidade dos dados
treino.nunique().sort_values(ascending=False)

PassengerId    891
Name           891
Ticket         681
Fare           248
Cabin          147
Age             88
SibSp            7
Parch            7
Embarked         3
Pclass           3
Survived         2
Sex              2
dtype: int64

In [17]:
# As colunas com alta cardinalidade como nome,ticket,cabine, nao vao ajudar o modelo pois pode torna-lo menos generalizavel nesse caso vamos eliminar essas colunas, pois eloas são colunas object (texto)

In [18]:
# eliminado para a base de treino
treino = treino.drop(["Name","Ticket","Cabin"], axis=1) #O parâmetro axis define se a remoção é de linhas ou colunas:
# axis=0 → remove linhas
# axis=1 → remove colunas
# nao eliminamos a coluna PassengerId porque iremos usar ela

In [19]:
# E eliminando tambem na base de teste (tudo que fizer na base de treino tem que fazer na base de teste)
teste = teste.drop(["Name","Ticket","Cabin"], axis=1)

In [20]:
# Agora precisamos tratar a coluna Age que tem valores vazios tanto no treino quanto no teste: No caso essa coluna não deveria ter valores vazios pois todo mundo tem uma idade.
# como essa coluna se refere a idade dos passageiros podemos fazer uma media de idade para preencher os valores vazios

# verificando a idade media da base de treino
treino.Age.mean()

np.float64(29.69911764705882)

In [21]:
# Agora podemos verificar as colunas com a idade vazia e substituir pela media de idade
treino.loc[treino.Age.isnull(), "Age"] = treino.Age.mean()
# treino.loc:Cria uma máscara booleana True onde Age é nulo.
# isnull(): Seleciona as linhas onde a condição é True e a coluna "Age".
# = mean() substitui os valores pela media da idade

In [22]:
# E fazendo o mesmo para a base de teste
teste.loc[teste.Age.isnull(), "Age"] = teste.Age.mean()

In [23]:
# Para a base de treino ainda temos 2 valores vazios na coluna "Embarked"
# Vamos verificar os valores vazios e substituir pela MODA (que é o valor mais frequente no caso dessa coluna é o S)

# verificando os valores na coluna Embarked
treino.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [24]:
# selecionando a moda dessa coluna
treino.Embarked.mode()[0]

'S'

In [25]:
# substituindo valores vazios 
treino.loc[treino.Embarked.isnull() , "Embarked"] = treino.Embarked.mode()[0]

In [26]:
# para finalizar a base de teste temos um arquivo vazio em Fare, vamos usar a mesma logica de Age e substituir pela moda
# verificando a media da coluna fare da base de teste

teste.loc[teste.Fare.isnull(),"Fare"] = teste.Fare.mean()

In [27]:
# Verificando novamente se ha dados vazios nas bases de treino e de teste
treino.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
dtype: int64

In [28]:
teste.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
dtype: int64

In [29]:
# Considerando apenas as colunas que nao sao texto:
# Verificando as colunas de texto na base:
treino.columns[treino.dtypes != 'object']

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [30]:
# selecionando apenas valores numericos da base de treino
col_treino_nr = treino.columns[treino.dtypes != 'object']
col_treino_nr

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [ ]:
# E para a base de treino,selecionando apenas valores numericos da base de teste
treino_nr = treino.loc[:, col_treino_nr]

In [32]:
# selecionando apenas valores numericos da base de teste 
# nao temos a coluna "Survived" porque é ela que queremos prever
col_teste_nr = teste.columns[teste.dtypes != 'object']
col_teste_nr

Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [33]:
# E para a base de teste selecionamos  apenas valores numericos da base de teste
teste_nr = teste.loc[:, col_teste_nr]

In [34]:
# Selecionando um modelo de Classificacao

# Nesse caso vamos selecionar 3 modelos :
# Arvore de Decisao - RandomForest
# Vizinhos Proximos - KNN 
# Regressão Logistica 

In [35]:
# Antes de usar esses modelos vamos separar a base em base de treino e validacao

# vamos importar o train_split_test

from sklearn.model_selection import train_test_split

In [46]:
# separando a base de treino em x e y
x = treino.drop(["PassengerId","Survived","Sex","Embarked"], axis=1)
y = treino.Survived

In [47]:
# separando em treino e validacao
x_train, x_val, y_train, y_val = train_test_split( x, y , test_size=0.33 , random_state=42)

In [48]:
# Para a arvore de classificao
# Fazendo a Importacao
from sklearn import tree 

In [49]:
# Criando o classificador
clf_ac = tree.DecisionTreeClassifier()

In [51]:
# fazendo o fit com os dados
clf_ac = clf_ac.fit(x_train, y_train)

In [52]:
# fazendo a previsao
y_pred_ac = clf_ac.predict(x_val)

In [53]:
# Para Vizinhos Proximos KNN
# Fazendo a importacao
from sklearn.neighbors import KNeighborsClassifier

In [54]:
# criando o classificador
clf_knn = KNeighborsClassifier(n_neighbors=3)

In [55]:
# fazendo o fit com os dados
clf_knn = clf_knn.fit(x_train, y_train)

In [56]:
# fazendo a previsao
y_pred_knn = clf_knn.predict(x_val)

In [57]:
# Para a regressao logistica
#fazendo a importacao
from sklearn.linear_model import LogisticRegression

In [58]:
# criando o calssificador
clf_rl = LogisticRegression(random_state=42)

In [59]:
# fazendo o fit com os dados
clf_rl = clf_rl.fit(x_train , y_train)

In [60]:
# fazendo a previsao
y_pred_rl = clf_rl.predict(x_val)

In [61]:
# Vamos fazer a avaliacao dos modelos 

# Accuracia
# Matriz de confusao (ajuda a avaliar a distribiucao de erros)

In [62]:
# avaliando a accuracia

# importacao
from sklearn.metrics import accuracy_score

In [63]:
# Para a Arvore de Classificacao
accuracy_score(y_val, y_pred_ac)

0.6203389830508474

In [65]:
# Para o KNN
accuracy_score(y_val, y_pred_knn)

0.6542372881355932

In [66]:
# Para a Regressao Logistica
accuracy_score(y_val, y_pred_rl)

0.7254237288135593

In [67]:
# Avaliando a Matriz de Confusao
# importacao
from sklearn.metrics import confusion_matrix

In [68]:
# para a arvore de classificacao
confusion_matrix(y_val, y_pred_ac)

array([[127,  48],
       [ 64,  56]])

In [69]:
# para o KNN
confusion_matrix(y_val, y_pred_knn)

array([[133,  42],
       [ 60,  60]])

In [70]:
# para a regressao logistica
confusion_matrix(y_val, y_pred_rl)

array([[156,  19],
       [ 62,  58]])

In [ ]:
# Fazendo a previsao para os dados de teste

In [71]:
x_train

Pclass        Age  SibSp  Parch      Fare
6         1  54.000000      0      0   51.8625
718       3  29.699118      0      0   15.5000
685       2  25.000000      1      2   41.5792
73        3  26.000000      1      0   14.4542
882       3  22.000000      0      0   10.5167
..      ...        ...    ...    ...       ...
106       3  21.000000      0      0    7.6500
270       1  29.699118      0      0   31.0000
860       3  41.000000      2      0   14.1083
435       1  14.000000      1      2  120.0000
102       1  21.000000      0      1   77.2875

[596 rows x 5 columns]

In [74]:
# Visualizando a base de teste Apenas com valores numericos:
teste_nr.head(3)

PassengerId  Pclass   Age  SibSp  Parch    Fare
0          892       3  34.5      0      0  7.8292
1          893       3  47.0      1      0  7.0000
2          894       2  62.0      0      0  9.6875

In [75]:
# para a base de teste ser igual a base de treino precisamos eliminar a coluna de PassengerId para isso...
x_teste = teste_nr.drop("PassengerId", axis=1)

In [76]:
# Utilizando a regressao logistica na base de teste
y_pred = clf_rl.predict(x_teste)

In [82]:
# Criando uma nova coluna com a previsao da base de teste
teste["Survived"] = y_pred

In [83]:
# selecionando a coluna passengerId e survived para submissao
base_envio = teste[["PassengerId", "Survived"]]


In [85]:
# exportando para um csv
base_envio.to_csv("Previsao_1",index=False)